real: True
quantiles_given: False
multiple_series: False 
T_burnin: 100 
alpha: 0.1
seasonal_period: 48
asymmetric: False
sequences:
  0:
    dataset: "elec2"
    fit_every: 48 
    log: False
    order:
      - 3 
      - 0 
      - 0
    window_length: 20 
    overwrite: False
methods:
  trail:
    weight_length: 50 
  aci:
    lrs:
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
    window_length: 10000000 
  quantile:
    lrs:
      - 0.5
      - 0.05
      - 0.01
      - 0.001
      - 0.0001
  quantile_integrator_log:
    lrs:
      - 0.5
      - 0.05
      - 0.01
      - 0.001
      - 0.0001
    Csat: 5 
    KI: 2 
  quantile_integrator_log_scorecaster:
    lrs:
      - 0.5 
      - 0.05
      - 0.01
      - 0.001
      - 0.0001
    Csat: 5
    KI: 2 
    steps_ahead: 1 
