real: False
Quantiles_given: False
multiple_series: False 
T_burnin: 1000
alpha: 0.1
asymmetric: False
sequences:
  0:
    category: "linear"
    start_point: 0
    end_point: 1 
    length: 1000
    sigma: 0.01
    dataset: "linear-0-1-1000-0.01"
methods:
  Trail:
    weight_length: 1000
  ACI:
    lrs:
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
    window_length: 10000000 
    T_burnin: 1000
  Quantile:
    lrs:
      - 0.2
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
  Quantile_integrator_log:
    lrs:
      - 0.2
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
    Csat: 5 
    KI: 10 
  Quantile_integrator_log_scorecaster:
    lrs:
      - 0.2
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
    Csat: 5 
    KI: 10 
    steps_ahead: 1
